# Generated by Django 5.0.4 on 2024-08-18 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('produtos', '0002_alter_produto_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('IdVenda', models.AutoField(primary_key=True, serialize=False)),
                ('DataVenda', models.DateField()),
                ('TotalVenda', models.FloatField(max_length=10)),
                ('Prazo', models.CharField(default='default', max_length=15)),
                ('Parcelas', models.IntegerField(default=1)),
                ('FormaPagamento', models.CharField(default='default', max_length=15)),
                ('IdCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['IdVenda'],
            },
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('IdItensVenda', models.AutoField(primary_key=True, serialize=False)),
                ('QtdProduto', models.IntegerField()),
                ('NomeProduto', models.CharField(default='default', max_length=255)),
                ('ValorUnitario', models.FloatField(max_length=10)),
                ('ValorTotal', models.FloatField(max_length=10)),
                ('IdProduto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('IdVenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_venda', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'ItenVenda',
                'verbose_name_plural': 'ItensVenda',
                'ordering': ['IdItensVenda'],
            },
        ),
    ]
