# Generated by Django 5.0.4 on 2024-11-20 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='DescontoPercentual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='venda',
            name='DescontoValor',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='TotalComDesconto',
            field=models.FloatField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='TotalSemDesconto',
            field=models.FloatField(default=0, max_length=10),
        ),
    ]
