# Generated by Django 5.0.4 on 2024-12-01 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0002_venda_descontopercentual_venda_descontovalor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='Estornada',
            field=models.BooleanField(default=False),
        ),
    ]
