# Generated by Django 5.0.4 on 2024-08-07 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_itensvenda_nomeproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='Prazo',
            field=models.CharField(default='Avistar', max_length=15),
        ),
    ]
