# Generated by Django 5.0.4 on 2024-08-07 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_venda_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='FormaPagamento',
            field=models.CharField(default='default', max_length=15),
        ),
        migrations.AlterField(
            model_name='venda',
            name='Prazo',
            field=models.CharField(default='default', max_length=15),
        ),
    ]
