# Generated by Django 5.0.4 on 2024-08-07 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_venda_formapagamento_alter_venda_prazo'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='Parcelas',
            field=models.IntegerField(default=0),
        ),
    ]
