# Generated by Django 5.0.4 on 2024-08-18 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('IdPessoa', models.AutoField(primary_key=True, serialize=False)),
                ('NomePessoa', models.CharField(max_length=255)),
                ('CPFcnpj', models.CharField(max_length=18)),
                ('NomeRua', models.CharField(max_length=255)),
                ('Numero', models.CharField(max_length=10)),
                ('NomeBairro', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Telefone', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['IdPessoa'],
            },
        ),
    ]
