# Generated by Django 5.0.4 on 2024-08-19 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='CPFcnpj',
            new_name='CPFouCNPJ',
        ),
    ]
