# Generated by Django 5.0.4 on 2024-12-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_cidade'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='Estado',
            field=models.CharField(default='default', max_length=25),
        ),
    ]
