# Generated by Django 5.0.4 on 2024-04-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('IdFornecedor', models.AutoField(primary_key=True, serialize=False)),
                ('NomeFantasia', models.CharField(max_length=255)),
                ('NomeJuridico', models.CharField(max_length=255)),
                ('CNPJ', models.CharField(max_length=18)),
                ('NomeRua', models.CharField(max_length=255)),
                ('Numero', models.CharField(max_length=10)),
                ('NomeBairro', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('Telefone', models.CharField(max_length=14)),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
                'ordering': ['IdFornecedor'],
            },
        ),
    ]
