# Generated by Django 5.0.4 on 2024-11-12 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fornecedores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='Cidade',
            field=models.CharField(default='default', max_length=25),
        ),
    ]
