# Generated by Django 5.0.4 on 2024-08-22 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_itenscompra_nomeproduto'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='FormaPagamento',
            field=models.CharField(default='default', max_length=15),
        ),
        migrations.AddField(
            model_name='compra',
            name='Parcelas',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='compra',
            name='Prazo',
            field=models.CharField(default='default', max_length=15),
        ),
    ]
