# Generated by Django 5.0.4 on 2024-04-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('IdProduto', models.AutoField(primary_key=True, serialize=False)),
                ('NomeProduto', models.CharField(max_length=255)),
                ('Descricao', models.CharField(max_length=255)),
                ('Preco', models.FloatField(max_length=10)),
                ('UnidMedida', models.CharField(max_length=20)),
                ('Estoque', models.IntegerField(max_length=20)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['IdProduto'],
            },
        ),
    ]
