# Generated by Django 5.0.4 on 2024-04-18 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='Estoque',
            field=models.IntegerField(),
        ),
    ]
