# Generated by Django 5.0.4 on 2024-11-20 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0002_initial'),
        ('vendas', '0002_venda_descontopercentual_venda_descontovalor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conta',
            name='Estornada',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EstornoLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DataEstorno', models.DateTimeField(auto_now_add=True)),
                ('Motivo', models.TextField()),
                ('IdVenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.venda')),
            ],
        ),
    ]
